function renderRekapPage(){if(GRAN!=='monthly'){let ex=currentExposure();$('rekapBody').innerHTML=`<div class="section-title">Rekap ${GRAN==='daily'?'Harian':'Mingguan'}</div><div class="hint">Incident quantity tetap dapat direkap per hari/minggu. Warehouse Rate yang tersedia dari SAP D+1 adalah <b>MTD PROVISIONAL</b>, bukan rate per hari/per minggu. Current MTD: <b>${ex?.rate_per_10000!=null?rate(ex.rate_per_10000)+' /10.000':'DATA REQUIRED'}</b> · ${esc(ex?.status||'DATA REQUIRED')}.</div>${$('scorecard').innerHTML}`;return}let exMap=Object.fromEntries((EXPOSURE?.rows||[]).map(x=>[x.rdc,x]));let rows=RDCROWS.map(r=>({...r,wx:exMap[r.rdc]||{}}));$('rekapBody').innerHTML=`<div class="section-title">Rekap Bulanan & RDC Comparison — ${monthName(PERIOD)}</div><div class="tablewrap"><table class="tbl"><thead><tr><th>RDC</th><th>Delivery Rate</th><th>Warehouse Rate</th><th>Warehouse Score</th><th>Data s.d.</th><th>Status Warehouse</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr><td>${esc(r.rdc)}</td><td>${rate(r.d_rate)}</td><td>${rate(r.wx.rate_per_10000)}</td><td>${r.wx.score==null?'—':scoreText(r.wx.score)}</td><td>${esc(r.wx.data_through_date||'—')}</td><td>${kpiStatusPill(r.wx.status||'DATA_REQUIRED')}</td></tr>`).join(''):`<tr><td colspan="6"><div class="empty">DATA REQUIRED</div></td></tr>`}</tbody></table></div><div style="margin-top:12px"><button class="secondary" onclick="exportExcel()">↓ Export Excel</button> <button class="secondary" onclick="window.print()">↓ Print / PDF</button></div>`}
function renderIncidentPage(){let rows=INCIDENTS;$('incidentBody').innerHTML=`<div class="section-title">Incident — ${monthName(PERIOD)} <span style="margin-left:auto"><button class="primary" onclick="openBreakageInput()">↗ Buka Breakage Input</button></span></div><div class="tablewrap"><table class="tbl"><thead><tr><th>Incident</th><th>Tanggal</th><th>RDC</th><th>Jenis</th><th>Item</th><th>Qty</th><th>No BA</th><th>Reported By</th><th>Status</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr><td>${esc(r.incident_no)}</td><td>${esc(r.occurrence_date)}</td><td>${esc(r.rdc)}</td><td>${esc(r.incident_type)}</td><td>${esc(r.item_code)}</td><td>${fmt(r.qty_box)} ${esc(r.uom)}</td><td>${esc(r.no_ba)}</td><td>${esc(r.reported_by)}</td><td><span class="status-pill ${String(r.status).toUpperCase()==='CLOSED'?'s-good':'s-watch'}">${esc(r.status)}</span></td></tr>`).join(''):`<tr><td colspan="9"><div class="empty">Belum ada incident pada periode ini.</div></td></tr>`}</tbody></table></div>`}
function renderReconPage(){let h=window.RECONH||[],mh=MOVEH||[],ex=currentExposure();$('reconBody').innerHTML=`
<div class="section-title">SAP Movement D+1 / MTD <span style="margin-left:auto"><button class="primary" onclick="openSapMove()">⇪ Upload SAP D+1 / MTD</button></span></div>
<div class="hint"><b>Daily/MTD = PROVISIONAL.</b> Recommended tarikan SAP: tanggal 1 bulan berjalan s.d. kemarin. Sistem dedupe transaksi yang sama. Unknown movement type harus dimapping agar denominator tidak salah.</div>
<div class="hl-strip" style="margin-top:10px"><div class="hl-item"><div><div class="smallnote">Opening Stock</div><b>${fmt(ex?.opening_stock)}</b><div class="smallnote">Box</div></div></div><div class="hl-item"><div><div class="smallnote">Stock In MTD</div><b>${fmt(ex?.stock_in)}</b><div class="smallnote">SAP mapped</div></div></div><div class="hl-item"><div><div class="smallnote">Stock Out MTD</div><b>${fmt(ex?.stock_out)}</b><div class="smallnote">SAP mapped</div></div></div><div class="hl-item"><div><div class="smallnote">Warehouse Exposure</div><b>${fmt(ex?.exposure)}</b><div class="smallnote">${esc(ex?.status||'DATA REQUIRED')}</div></div></div></div>
<div class="tablewrap" style="margin-top:10px"><table class="tbl"><thead><tr><th>Upload</th><th>RDC</th><th>Mode</th><th>Data s.d.</th><th>Rows</th><th>Mapped</th><th>Review</th><th>Status</th></tr></thead><tbody>${mh.length?mh.slice(0,20).map(r=>`<tr><td>${esc(r.filename)}</td><td>${esc(r.rdc)}</td><td>${esc(r.mode)}</td><td>${esc(r.data_through_date)}</td><td>${fmt(r.total_rows)}</td><td>${fmt(r.mapped_rows)}</td><td>${fmt(r.review_rows)}</td><td>${kpiStatusPill(r.status==='READY'?'PROVISIONAL':r.status)}</td></tr>`).join(''):`<tr><td colspan="8"><div class="empty">Belum ada upload SAP Movement D+1 / MTD.</div></td></tr>`}</tbody></table></div>
<div class="section-title" style="margin-top:22px">Monthly Reconciliation — SAP MB51 <span style="margin-left:auto"><button class="secondary" onclick="openRecon()">Start Final Reconciliation</button></span></div>
<div class="hint">Akhir bulan: full MB51 + reconciliation. Setelah review & publish, KPI bulan menjadi <b>FINAL</b>. Daily Incident adalah case-level control; SAP MB51 adalah transactional control; jangan double count.</div>
<div class="tablewrap" style="margin-top:12px"><table class="tbl"><thead><tr><th>Periode</th><th>RDC</th><th>File</th><th>Rows</th><th>Status</th><th>Upload</th><th>Publish</th></tr></thead><tbody>${h.length?h.map(r=>`<tr><td>${esc(r.period)}</td><td>${esc(r.rdc)}</td><td>${esc(r.filename)}</td><td>${fmt(r.total_rows)}</td><td>${esc(r.status)}</td><td>${esc(r.uploaded_at)}</td><td>${esc(r.published_at||'—')}</td></tr>`).join(''):`<tr><td colspan="7"><div class="empty">Belum ada reconciliation history.</div></td></tr>`}</tbody></table></div>`}
function renderTargetPage(){let a=TARGETS,md=managementSetting('delivery'),mw=managementSetting('warehouse'),mr=managementSetting('receiving'),cs=cutoffSummary();$('targetBody').innerHTML=`
<div class="section-title">Setting Target KPI & Revision Control <span style="margin-left:auto">${ACCESS?.is_master?'<button class="primary" onclick="openKpiSetting()">⚙ Setting Target Utama</button> <button class="secondary" onclick="openTarget()">＋ Revisi Recovery Target</button>':''}</span></div>
<div class="hint">Target Utama Management dan Recovery Target disimpan terpisah. Semua perubahan versioned; target lama tidak dihapus.</div>
<div class="hl-strip" style="margin-top:12px">
 <div class="hl-item"><div><div class="smallnote">Delivery · Target Utama</div><b>${md?.target_rate_per_10000!=null?'≤ '+fmt(md.target_rate_per_10000)+' /10.000':'DATA REQUIRED'}</b><div class="smallnote">${md?esc(md.denominator_label):''}</div></div></div>
 <div class="hl-item"><div><div class="smallnote">Warehouse · Target Utama</div><b>${mw?.target_pct!=null?'≤ '+pct4(mw.target_pct)+'%':'DATA REQUIRED'}</b><div class="smallnote">${mw?.target_rate_per_10000!=null?fmt(mw.target_rate_per_10000)+' /10.000 · ':''}${mw?esc(mw.denominator_label):''}</div></div></div>
 <div class="hl-item"><div><div class="smallnote">Receiving</div><b>Qty Only</b><div class="smallnote">${mr?esc(mr.denominator_label):'Denominator belum authoritative'}</div></div></div>
 <div class="hl-item"><div><div class="smallnote">Score KPI Breakage</div><b class="good">FORMULA ACTIVE</b><div class="smallnote">Warehouse KPI resmi. Score mulai setelah cut-off + flow Stock In/Out tersedia.</div></div></div>
</div>
<div class="section-title" style="margin-top:16px">Go-Live Readiness — Cut-off Stock <span style="margin-left:auto">${ACCESS?.is_master?'<button class="primary" onclick="openCutoff()">＋ Set / Revisi Cut-off</button>':''}</span></div>
<div class="hint"><b>${cs.ready}/${cs.total} RDC cut-off ready.</b> Opening balance wajib ditetapkan sebelum go-live. Stock current yang berubah-ubah bukan pengganti cut-off.</div>
<div class="tablewrap" style="margin-top:8px"><table class="tbl"><thead><tr><th>RDC</th><th>Tanggal Cut-off</th><th>Opening Stock</th><th>Source</th><th>Revision</th><th>Status</th></tr></thead><tbody>${CUTOFFS.map(c=>`<tr><td>${esc(c.rdc)}</td><td>${esc(c.cutoff_date||'—')}</td><td>${c.opening_stock_box==null?'—':fmt(c.opening_stock_box)+' Box'}</td><td>${esc(c.source||'—')}</td><td>${c.revision_no?'Rev '+c.revision_no:'—'}</td><td>${c.status==='READY'?'<span class="status-pill s-good">READY</span>':'<span class="status-pill s-bad">CUT-OFF REQUIRED</span>'}</td></tr>`).join('')}</tbody></table></div>
<div class="section-title" style="margin-top:16px">Recovery Target Sep–Okt 2026</div>
<div class="tablewrap" style="margin-top:8px"><table class="tbl"><thead><tr><th>Period</th><th>Window</th><th>KPI</th><th>Scope</th><th>Recovery Target</th><th>Revision</th><th>Updated By</th></tr></thead><tbody>${a.map(t=>`<tr><td>${esc(t.period_key)}</td><td>${esc(t.window_label)}</td><td>${esc(t.kpi_code)}</td><td>${esc(t.scope_rdc)}</td><td>≤ ${fmt(t.target_value)} /10.000</td><td>Rev ${t.revision_no}</td><td>${esc(t.created_by_name||'—')}</td></tr>`).join('')}</tbody></table></div>`}
function openBreakageInput(){window.open(BREAKAGE_INPUT_URL,'_blank')} window.openBreakageInput=openBreakageInput;
function renderAll(){setupWindow();renderKpis();renderTargetWindow();renderBaselinePanel();renderScorecard();renderTrend();renderActions();renderRekapPage();renderIncidentPage();renderReconPage();renderTargetPage();$('who').textContent=`${String(ACCESS.role||'').toUpperCase()} · ${ACCESS.is_master?'Nasional':ACCESS.rdc_name}`;$('pageTitle').textContent=`Monitoring Breakage ${SCOPE==='ALL'?'Nasional':SCOPE}`;$('targetBtn').classList.toggle('hidden',!ACCESS.is_master);$('inputBtn').classList.remove('hidden');$('sapMoveBtn').classList.toggle('hidden',!['master','rdc_manager','supervisor'].includes(ACCESS?.role));if(!ACCESS.is_master){$('scope').innerHTML=`<option>${esc(ACCESS.rdc_name)}</option>`;$('scopeCtrl').querySelector('select').disabled=true}}
function showPage(p){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id==='page-'+p));document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===p))}
window.showPage=showPage;
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
$('gran').querySelectorAll('button').forEach(b=>b.onclick=()=>{GRAN=b.dataset.g;$('gran').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));setupWindow();renderKpis();renderScorecard();renderRekapPage()});
$('period').onchange=async e=>{PERIOD=e.target.value;await loadAll()};$('scope').onchange=async e=>{SCOPE=e.target.value;await loadAll()};$('windowSel').onchange=()=>{renderKpis();renderScorecard()};
$('ctBtn').onclick=()=>window.open('https://sls-supply-chain-control-tower.vercel.app/','_blank');$('logoutBtn').onclick=async()=>{try{if(SESSION?.access_token)await fetch(`${SUPABASE_URL}/auth/v1/logout`,{method:'POST',headers:{apikey:PUBLIC_ANON,Authorization:`Bearer ${SESSION.access_token}`}})}catch(_){}sessionStorage.removeItem('sls_breakage_session');sessionStorage.removeItem('sls_breakage_username');location.reload()};
// login
$('loginBtn').onclick=login;['username','pw'].forEach(id=>$(id).onkeydown=e=>{if(e.key==='Enter')login()});
async function login(){let username=$('username').value.trim(),pw=$('pw').value;$('loginMsg').textContent='';if(!username||!pw){$('loginMsg').textContent='User ID dan password wajib.';return}try{await signIn(username,pw);PERIOD='2026-09';SCOPE=ACCESS.is_master?'ALL':ACCESS.rdc_name;initPeriods();$('login').style.display='none';$('app').style.display=window.innerWidth<=760?'block':'grid';await loadAll()}catch(e){$('loginMsg').textContent=cleanErr(e.message)}}
async function restoreSession(){initPeriods();$('username').value=sessionStorage.getItem('sls_breakage_username')||'';let raw=sessionStorage.getItem('sls_breakage_session');if(!raw)return;try{SESSION=JSON.parse(raw);if(!SESSION?.access_token)throw new Error('invalid session');ACCESS=await rpc('breakage_my_access_v44',{});PERIOD='2026-09';SCOPE=ACCESS.is_master?'ALL':ACCESS.rdc_name;$('login').style.display='none';$('app').style.display=window.innerWidth<=760?'block':'grid';await loadAll()}catch(e){sessionStorage.removeItem('sls_breakage_session')}}
restoreSession();
// modal generic
