document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).classList.remove('show'));$('inputBtn').onclick=openBreakageInput;$('targetBtn').onclick=openKpiSetting;$('sapMoveBtn').onclick=openSapMove;
function openInput(){if(!ACCESS?.can_input){alert('Role ini tidak memiliki hak input incident.');return}$('incidentModal').classList.add('show');$('fRdc').value=ACCESS.is_master?(SCOPE==='ALL'?'Pilih RDC via scope terlebih dahulu':SCOPE):ACCESS.rdc_name;$('fInputBy').value=ACCESS.username||ACCESS.role;$('inputIdentity').textContent=`${String(ACCESS.role).toUpperCase()} · ${$('fRdc').value}`;$('fDate').value=new Date().toISOString().slice(0,10);restoreDraft();renderConditional('delivery');renderPhotos()}
window.openInput=openInput;
let TYPE='delivery',CAUSE='Perjalanan',PHOTOS=[];function renderConditional(t){TYPE=t;document.querySelectorAll('#typeTabs button').forEach(b=>b.classList.toggle('active',b.dataset.type===t));let el=$('conditional');if(t==='delivery')el.innerHTML=`<div class="form-grid"><div class="field"><label>No SJ *</label><input id="fSj"></div><div class="field"><label>Customer *</label><input id="fCustomer"></div><div class="field"><label>Transporter *</label><input id="fTransporter"></div><div class="field"><label>Driver *</label><input id="fDriver"></div><div class="field span2"><label>No Polisi *</label><input id="fPolice"></div></div>`;else if(t==='receiving')el.innerHTML=`<div class="form-grid"><div class="field"><label>No SJ *</label><input id="fSj"></div><div class="field"><label>Factory *</label><select id="fFactory"><option value="">Pilih</option><option>SRKI</option><option>RCI</option></select></div><div class="field"><label>Transporter *</label><input id="fTransporter"></div><div class="field"><label>Driver *</label><input id="fDriver"></div><div class="field span2"><label>No Polisi *</label><input id="fPolice"></div></div>`;else el.innerHTML=`<div class="form-grid"><div class="field"><label>Kejadian Gudang *</label><select id="fWhEvent"><option value="Pecah Dalam Pallet">Pecah Dalam Pallet</option><option value="Misshandling">Misshandling</option></select></div><div class="field"><label>Nama terkait (wajib jika Misshandling)</label><input id="fRelated"></div></div>`;bindDraftInputs()}
$('typeTabs').querySelectorAll('button').forEach(b=>b.onclick=()=>renderConditional(b.dataset.type));$('causeTabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{CAUSE=b.dataset.cause;$('causeTabs').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));saveDraft()});
function formData(){return {type:TYPE,cause:CAUSE,date:$('fDate').value,ba:$('fBa').value,item:$('fItem').value,qty:$('fQty').value,reported:$('fReported').value,sj:$('fSj')?.value||'',factory:$('fFactory')?.value||'',customer:$('fCustomer')?.value||'',transporter:$('fTransporter')?.value||'',driver:$('fDriver')?.value||'',police:$('fPolice')?.value||'',wh:$('fWhEvent')?.value||'',related:$('fRelated')?.value||'',detail:$('fCauseDetail').value}}
function saveDraft(){localStorage.setItem('sls_breakage_incident_draft',JSON.stringify(formData()));$('draftStatus').textContent='☁ Draft otomatis tersimpan'}
function restoreDraft(){try{let d=JSON.parse(localStorage.getItem('sls_breakage_incident_draft')||'{}');TYPE=d.type||'delivery';CAUSE=d.cause||'Perjalanan';renderConditional(TYPE);[['fDate','date'],['fBa','ba'],['fItem','item'],['fQty','qty'],['fReported','reported'],['fCauseDetail','detail']].forEach(([id,k])=>{if(d[k])$(id).value=d[k]});setTimeout(()=>{[['fSj','sj'],['fFactory','factory'],['fCustomer','customer'],['fTransporter','transporter'],['fDriver','driver'],['fPolice','police'],['fWhEvent','wh'],['fRelated','related']].forEach(([id,k])=>{if($(id)&&d[k])$(id).value=d[k]})},0);$('causeTabs').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.cause===CAUSE))}catch{}}
function bindDraftInputs(){document.querySelectorAll('#incidentModal input,#incidentModal select,#incidentModal textarea').forEach(x=>{if(x.id!=='fPhotos')x.oninput=saveDraft})}bindDraftInputs();$('saveDraft').onclick=saveDraft;
$('fPhotos').onchange=e=>{let arr=Array.from(e.target.files||[]);if(arr.length>5){alert('Maksimal 5 foto.');e.target.value='';return}PHOTOS=arr;renderPhotos()};function renderPhotos(){$('photoPreview').innerHTML=[0,1,2,3,4].map(i=>`<div class="ph">${PHOTOS[i]?`<img src="${URL.createObjectURL(PHOTOS[i])}"><b>${i+1}</b>`:`<b>${i+1}</b>`}</div>`).join('')}
function validateIncident(){let d=formData(),m=[];if(!d.date)m.push('Tanggal');if(!d.ba)m.push('No BA');if(!d.item)m.push('Kode Item');if(!(Number(d.qty)>0))m.push('Qty');if(!d.reported)m.push('Reported By');if(PHOTOS.length<1)m.push('Foto');if(TYPE==='delivery'){if(!d.sj)m.push('No SJ');if(!d.customer)m.push('Customer');if(!d.transporter)m.push('Transporter');if(!d.driver)m.push('Driver');if(!d.police)m.push('No Polisi')}if(TYPE==='receiving'){if(!d.sj)m.push('No SJ');if(!d.factory)m.push('Factory');if(!d.transporter)m.push('Transporter');if(!d.driver)m.push('Driver');if(!d.police)m.push('No Polisi')}if(TYPE==='warehouse'&&d.wh==='Misshandling'&&!d.related)m.push('Nama terkait');if(CAUSE==='Lainnya'&&!d.detail)m.push('Keterangan penyebab');return m}
async function uploadEvidence(files,rdc){let batch='draft_'+crypto.randomUUID(),paths=[];for(let i=0;i<files.length;i++){let f=files[i],ext=(f.name.split('.').pop()||'jpg').toLowerCase(),safe=String(rdc).replace(/[^A-Za-z0-9_-]/g,'_'),path=`${safe}/${batch}/${Date.now()}_${i+1}.${ext}`;let r=await fetch(`${SUPABASE_URL}/storage/v1/object/breakage-evidence/${encodeURI(path)}`,{method:'POST',headers:{apikey:PUBLIC_ANON,Authorization:`Bearer ${auth()}`,'Content-Type':f.type||'image/jpeg','x-upsert':'false'},body:f});if(!r.ok)throw new Error('Upload foto gagal: '+await r.text());paths.push(path)}return paths}
$('submitIncident').onclick=async()=>{let miss=validateIncident(),msg=$('inputMsg');if(miss.length){msg.classList.remove('hidden');msg.textContent='Mohon lengkapi: '+miss.join(', ');return}if(ACCESS.is_master&&SCOPE==='ALL'){msg.classList.remove('hidden');msg.textContent='Master harus memilih RDC pada scope sebelum input.';return}let b=$('submitIncident');b.disabled=true;msg.classList.remove('hidden');msg.textContent='Menyimpan evidence dan incident…';try{let d=formData(),rdc=ACCESS.is_master?SCOPE:ACCESS.rdc_name,paths=await uploadEvidence(PHOTOS,rdc);let payload={incident_type:TYPE,occurrence_date:d.date,item_code:d.item,qty_box:Number(d.qty),uom:'BOX',rdc_name:rdc,no_ba:d.ba.toUpperCase(),reported_by:d.reported,no_sj:d.sj,factory:d.factory,customer:d.customer,transporter:d.transporter,driver_name:d.driver,vehicle_no:d.police.toUpperCase(),cause:CAUSE,cause_detail:d.detail,warehouse_event:d.wh,related_person:d.related,photo_paths:paths};let res=await rpc('breakage_incident_create_v44',{p_payload:payload});msg.style.color='#079455';msg.textContent=`✓ Tersimpan ${res.incident_no} · BA ${res.no_ba}`;localStorage.removeItem('sls_breakage_incident_draft');PHOTOS=[];setTimeout(async()=>{$('incidentModal').classList.remove('show');await loadAll();showPage('incident')},900)}catch(e){msg.style.color='#c42d26';msg.textContent='Gagal: '+cleanErr(e.message)}finally{b.disabled=false}};
// management KPI setting modal
function denomOptions(kpi){
 if(kpi==='warehouse')return [['OPENING_PLUS_IN_PLUS_OUT','Stock Awal + Stock In + Stock Out']];
 if(kpi==='delivery')return [['DELIVERED_BOX','Delivered Box']];
 return [['QTY_ONLY','Qty / Control Volume only']];
}
function syncMgmtDenom(){let k=$('mKpi').value;$('mDenom').innerHTML=denomOptions(k).map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('');prefillMgmtSetting()}
function prefillMgmtSetting(){let k=$('mKpi').value,s=$('mScope').value,m=KPI_SETTINGS.find(x=>x.kpi_code===k&&(x.scope_rdc===s||x.scope_rdc==='ALL'));$('mRate').value=m?.target_rate_per_10000??'';$('mPct').value=m?.target_pct??'';if(m?.denominator_method&&[...$('mDenom').options].some(o=>o.value===m.denominator_method))$('mDenom').value=m.denominator_method;let note=k==='warehouse'?'Formula KPI: Qty Pecah Gudang ÷ (Stock Awal + Stock In + Stock Out) × 100%. Target awal management = 0,0200% = 2,00 /10.000 exposure.':k==='delivery'?'Formula KPI: Qty Pecah Kiriman ÷ Delivered Box × 10.000. Target awal = 3,68 /10.000 delivered.':'Receiving tetap Qty/control volume sampai denominator authoritative disetujui.';$('mFormulaNote').innerHTML=note;if(k==='receiving'){$('mRate').disabled=true;$('mPct').disabled=true}else{$('mRate').disabled=false;$('mPct').disabled=false}}
async function openKpiSetting(){if(!ACCESS?.is_master){alert('Hanya Master dapat mengubah Setting Target KPI.');return}$('kpiSettingModal').classList.add('show');$('mScope').value=SCOPE==='ALL'?'ALL':SCOPE;syncMgmtDenom();await loadMgmtHistory()};window.openKpiSetting=openKpiSetting;
$('mKpi').onchange=syncMgmtDenom;$('mScope').onchange=prefillMgmtSetting;
$('mRate').oninput=()=>{if(document.activeElement===$('mRate')&&$('mRate').value!=='')$('mPct').value=(Number($('mRate').value)/100).toFixed(4)};
$('mPct').oninput=()=>{if(document.activeElement===$('mPct')&&$('mPct').value!=='')$('mRate').value=(Number($('mPct').value)*100).toFixed(2)};
async function loadMgmtHistory(){try{let h=await rpc('breakage_kpi_setting_history_v48',{p_scope:$('mScope').value});$('mSettingHistory').innerHTML=`<div class="tablewrap"><table class="tbl"><thead><tr><th>KPI</th><th>Scope</th><th>Target %</th><th>/10.000</th><th>Denominator</th><th>Rev</th><th>Status</th><th>By</th></tr></thead><tbody>${h.slice(0,30).map(x=>`<tr><td>${esc(x.kpi_code)}</td><td>${esc(x.scope_rdc)}</td><td>${x.target_pct==null?'—':pct4(x.target_pct)+'%'}</td><td>${x.target_rate_per_10000==null?'—':fmt(x.target_rate_per_10000)}</td><td>${esc(x.denominator_label)}</td><td>${x.revision_no}</td><td>${esc(x.status)}</td><td>${esc(x.created_by_name||'—')}</td></tr>`).join('')}</tbody></table></div>`}catch(e){$('mSettingHistory').textContent=cleanErr(e.message)}}
$('saveKpiSetting').onclick=async()=>{let k=$('mKpi').value,den=$('mDenom').selectedOptions[0],payload={kpi_code:k,scope_rdc:$('mScope').value,target_rate_per_10000:k==='receiving'?null:Number($('mRate').value),target_pct:k==='receiving'?null:Number($('mPct').value),denominator_method:$('mDenom').value,denominator_label:den?.textContent||'',revision_reason:$('mReason').value.trim()},msg=$('mSettingMsg');if(!payload.revision_reason||(k!=='receiving'&&(!(payload.target_rate_per_10000>=0)||!(payload.target_pct>=0)))){msg.classList.remove('hidden');msg.style.color='#c42d26';msg.textContent='Target dan alasan revisi wajib diisi.';return}try{let r=await rpc('breakage_kpi_setting_save_v48',{p_payload:payload});msg.classList.remove('hidden');msg.style.color='#079455';msg.textContent=`✓ Setting ${k} tersimpan sebagai Revision ${r.revision_no}`;KPI_SETTINGS=await rpc('breakage_kpi_settings_v48',{p_scope:SCOPE});await loadMgmtHistory();renderAll()}catch(e){msg.classList.remove('hidden');msg.style.color='#c42d26';msg.textContent='Gagal: '+cleanErr(e.message)}};


// Go-Live Cut-off Stock
async function loadCutoffHistory(){try{let h=await rpc('breakage_cutoff_history_v50',{p_rdc:$('cRdc').value});$('cHistory').innerHTML=`<div class="tablewrap"><table class="tbl"><thead><tr><th>RDC</th><th>Tanggal</th><th>Opening Stock</th><th>Source</th><th>Rev</th><th>Status</th><th>By</th></tr></thead><tbody>${h.slice(0,30).map(x=>`<tr><td>${esc(x.rdc)}</td><td>${esc(x.cutoff_date)}</td><td>${fmt(x.opening_stock_box)} Box</td><td>${esc(x.source)}</td><td>${x.revision_no}</td><td>${esc(x.status)}</td><td>${esc(x.created_by_name||'—')}</td></tr>`).join('')}</tbody></table></div>`}catch(e){$('cHistory').textContent=cleanErr(e.message)}}
