function prefillCutoff(){let r=$('cRdc').value,c=CUTOFFS.find(x=>x.rdc===r&&x.status==='READY');$('cDate').value=c?.cutoff_date||'';$('cStock').value=c?.opening_stock_box??'';$('cSource').value=c?.source||'SAP_CUTOFF';$('cRef').value=c?.source_reference||'';loadCutoffHistory()}
async function openCutoff(){if(!ACCESS?.is_master){alert('Hanya Master dapat menetapkan cut-off stock.');return}$('cutoffModal').classList.add('show');$('cRdc').value=SCOPE==='ALL'?'Jakarta':SCOPE;prefillCutoff()}window.openCutoff=openCutoff;
$('cRdc').onchange=prefillCutoff;
$('saveCutoff').onclick=async()=>{let payload={rdc_name:$('cRdc').value,cutoff_date:$('cDate').value,opening_stock_box:Number($('cStock').value),source:$('cSource').value,source_reference:$('cRef').value.trim(),revision_reason:$('cReason').value.trim()},msg=$('cMsg');if(!payload.cutoff_date||!(payload.opening_stock_box>=0)||!payload.revision_reason){msg.classList.remove('hidden');msg.style.color='#c42d26';msg.textContent='Tanggal cut-off, opening stock dan catatan wajib diisi.';return}try{let r=await rpc('breakage_cutoff_save_v50',{p_payload:payload});msg.classList.remove('hidden');msg.style.color='#079455';msg.textContent=`✓ Cut-off ${r.rdc} tersimpan sebagai Revision ${r.revision_no}`;CUTOFFS=await rpc('breakage_cutoff_status_v50',{p_scope:SCOPE});await loadCutoffHistory();renderAll()}catch(e){msg.classList.remove('hidden');msg.style.color='#c42d26';msg.textContent='Gagal: '+cleanErr(e.message)}};

// target modal
function windowOptions(period){return period==='2026-09'?[['W1-W2',1,'W1–W2 · Baseline / Control'],['W3-W4',2,'W3–W4 · End Sep']]:[['W5-W6',3,'W5–W6 · Target'],['W7-W8',4,'W7–W8 · End Oct']]}
function syncTargetWindow(){let p=$('tPeriod').value;$('tWindow').innerHTML=windowOptions(p).map(x=>`<option value="${x[0]}" data-order="${x[1]}" data-label="${x[2]}">${x[2]}</option>`).join('');prefillTarget()}
function prefillTarget(){let k=$('tKpi').value,p=$('tPeriod').value,w=$('tWindow').value,s=$('tScope').value,t=TARGETS.find(x=>x.kpi_code===k&&x.period_key===p&&x.window_code===w&&(x.scope_rdc===s||x.scope_rdc==='ALL'));$('tValue').value=t?.target_value??'';$('tObjective').value=t?.objective??''}
async function openTarget(){if(!ACCESS?.is_master){alert('Hanya Master dapat mengubah target KPI.');return}$('targetModal').classList.add('show');syncTargetWindow();await loadTargetHistory()};window.openTarget=openTarget;
['tKpi','tScope','tPeriod','tWindow'].forEach(id=>$(id).onchange=()=>{if(id==='tPeriod')syncTargetWindow();else prefillTarget()});async function loadTargetHistory(){try{let h=await rpc('breakage_target_history_v45',{p_scope:$('tScope').value});$('targetHistory').innerHTML=`<table class="tbl"><thead><tr><th>Window</th><th>KPI</th><th>Scope</th><th>Target</th><th>Rev</th><th>Status</th><th>By</th></tr></thead><tbody>${h.slice(0,20).map(x=>`<tr><td>${esc(x.window_label)}</td><td>${esc(x.kpi_code)}</td><td>${esc(x.scope_rdc)}</td><td>${fmt(x.target_value)}</td><td>${x.revision_no}</td><td>${esc(x.status)}</td><td>${esc(x.created_by_name||'—')}</td></tr>`).join('')}</tbody></table>`}catch(e){$('targetHistory').textContent=cleanErr(e.message)}}
$('saveTarget').onclick=async()=>{let sel=$('tWindow').selectedOptions[0],payload={program_code:'BREAKAGE_REDUCTION_SEP_OCT_2026',period_key:$('tPeriod').value,window_code:$('tWindow').value,window_order:Number(sel.dataset.order),window_label:sel.dataset.label,kpi_code:$('tKpi').value,scope_rdc:$('tScope').value,target_value:Number($('tValue').value),objective:$('tObjective').value,revision_reason:$('tReason').value},msg=$('targetMsg');if(!payload.revision_reason||!(payload.target_value>=0)){msg.classList.remove('hidden');msg.textContent='Target dan alasan revisi wajib diisi.';return}try{let r=await rpc('breakage_target_save_v45',{p_payload:payload});msg.classList.remove('hidden');msg.style.color='#079455';msg.textContent=`✓ Target tersimpan sebagai Revision ${r.revision_no}`;TARGETS=await rpc('breakage_target_matrix_v45',{p_scope:SCOPE});await loadTargetHistory();renderAll()}catch(e){msg.classList.remove('hidden');msg.style.color='#c42d26';msg.textContent='Gagal: '+cleanErr(e.message)}};
// SAP Movement D+1 / MTD exposure pipeline v51
function hdrIndex(h,names){for(const n of names){let i=h.findIndex(x=>String(x||'').trim().toLowerCase()===String(n).toLowerCase());if(i>=0)return i}return -1}
function normRdc(v){return String(v||'').trim().replace(/^RDC\s+/i,'').replace(/\s+/g,' ').replace(/^JAKARTA$/i,'Jakarta').replace(/^SEMARANG$/i,'Semarang').replace(/^SURABAYA$/i,'Surabaya').replace(/^DENPASAR$/i,'Denpasar').replace(/^PALEMBANG$/i,'Palembang')}
function parseMovementMB51(wb){let sn=wb.SheetNames.find(n=>{let g=XLSX.utils.sheet_to_json(wb.Sheets[n],{header:1,defval:null}),h=(g[0]||[]).map(x=>String(x||'').trim().toLowerCase());return h.includes('posting date')&&h.includes('movement type')&&h.includes('quantity')});if(!sn)return null;let g=XLSX.utils.sheet_to_json(wb.Sheets[sn],{header:1,defval:null,raw:true,cellDates:true}),h=(g[0]||[]).map(x=>String(x||'').trim());let cd=hdrIndex(h,['Posting Date']),cm=hdrIndex(h,['Movement Type','MvT']),cq=hdrIndex(h,['Quantity','Qty']),cs=hdrIndex(h,['Storage Location','SLoc']),cr=hdrIndex(h,['Name 1','RDC','Plant Name']),cma=hdrIndex(h,['Material']),cb=hdrIndex(h,['Batch']),cdo=hdrIndex(h,['Material Document','Mat. Doc.']),citem=hdrIndex(h,['Material Doc.Item','Material Document Item','Mat. Doc. Item','Item']),ch=hdrIndex(h,['Document Header Text','Doc.Header Text']);if([cd,cm,cq,cr].some(i=>i<0))return null;let out=[];for(let i=1;i<g.length;i++){let r=g[i],d=r[cd],mt=String(r[cm]||'').trim(),qty=Math.abs(Number(r[cq])||0),rdc=normRdc(r[cr]);if(!(d instanceof Date)||!mt||!qty||!rdc)continue;out.push({rdc_name:rdc,posting_date:d.toISOString().slice(0,10),movement_type:mt,qty_abs:qty,storage_location:cs>=0?String(r[cs]||'').trim():'',material_code:cma>=0?String(r[cma]||'').trim():'',batch_no:cb>=0?String(r[cb]||'').trim():'',sap_document:cdo>=0?String(r[cdo]||'').trim():'',document_item:citem>=0?String(r[citem]||'').trim():'',document_header_text:ch>=0?String(r[ch]||'').trim():''})}return out.length?out:null}
async function openSapMove(){if(!['master','rdc_manager','supervisor'].includes(ACCESS?.role)){alert('Role tidak memiliki hak upload SAP movement.');return}$('sapMoveModal').classList.add('show');$('smMsg').classList.add('hidden');$('smPreview').innerHTML='';await loadMovementMap()}window.openSapMove=openSapMove;
async function loadMovementMap(){try{MOVEMAP=await rpc('breakage_movement_mapping_v51',{});$('smMapping').innerHTML=`<div class="tablewrap"><table class="tbl"><thead><tr><th>MvT</th><th>Klasifikasi</th><th>Factor</th><th>Catatan</th><th></th></tr></thead><tbody>${MOVEMAP.map(m=>`<tr><td><b>${esc(m.movement_type)}</b></td><td>${esc(m.exposure_bucket)}</td><td>${fmt(m.factor)}</td><td>${esc(m.notes||'—')}</td><td>${ACCESS?.is_master?`<button class="secondary" onclick="editMoveMap('${esc(m.movement_type)}')">Edit</button>`:''}</td></tr>`).join('')}</tbody></table></div>`}catch(e){$('smMapping').textContent=cleanErr(e.message)}}
function editMoveMap(mt){let m=MOVEMAP.find(x=>x.movement_type===mt)||{movement_type:mt,exposure_bucket:'REVIEW',factor:0,notes:''};$('mmType').value=mt;$('mmBucket').value=m.exposure_bucket;$('mmFactor').value=String(m.factor);$('mmNotes').value=m.notes||'';$('mmMsg').classList.add('hidden');syncMoveFactor();$('movementMapModal').classList.add('show')}window.editMoveMap=editMoveMap;
function syncMoveFactor(){let b=$('mmBucket').value;if(!['IN','OUT'].includes(b)){$('mmFactor').value='0';$('mmFactor').disabled=true}else $('mmFactor').disabled=false}
$('mmBucket').onchange=syncMoveFactor;
$('saveMoveMap').onclick=async()=>{let msg=$('mmMsg'),payload={movement_type:$('mmType').value,exposure_bucket:$('mmBucket').value,factor:Number($('mmFactor').value),notes:$('mmNotes').value.trim()};try{await rpc('breakage_movement_map_save_v51',{p_payload:payload});msg.classList.remove('hidden');msg.style.color='#079455';msg.textContent='✓ Mapping tersimpan. Movement existing juga direclassify.';await loadMovementMap();setTimeout(()=>{$('movementMapModal').classList.remove('show')},500);await loadAll()}catch(e){msg.classList.remove('hidden');msg.style.color='#c42d26';msg.textContent='Gagal: '+cleanErr(e.message)}};
$('smFile').onchange=e=>{if(e.target.files[0])handleMovementFile(e.target.files[0])};
function handleMovementFile(file){let msg=$('smMsg');msg.classList.remove('hidden');msg.style.color='#6f7b91';msg.textContent='Membaca MB51 movement…';let fr=new FileReader();fr.onload=async e=>{try{let wb=XLSX.read(e.target.result,{type:'binary',cellDates:true}),rows=parseMovementMB51(wb);if(!rows)throw new Error('MB51 tidak dikenali. Pastikan Posting Date, Movement Type, Quantity dan Name 1/RDC tersedia.');let groups={};for(const r of rows){let period=r.posting_date.slice(0,7),k=r.rdc_name+'|'+period;(groups[k]||(groups[k]=[])).push(r)}let results=[];for(const [k,rr] of Object.entries(groups)){let [rdc,period]=k.split('|');if(!RDC_LIST.includes(rdc))continue;if(period!==PERIOD)continue;if(!ACCESS.is_master&&rdc!==ACCESS.rdc_name)continue;results.push(await rpc('breakage_movement_stage_v51',{p_filename:file.name,p_mode:$('smMode').value,p_rows:rr}))}if(!results.length)throw new Error(`Tidak ada baris ${PERIOD} untuk scope login/RDC yang valid.`);let reviews=results.reduce((a,b)=>a+Number(b.review_rows||0),0);$('smPreview').innerHTML=`<div class="section-title">Hasil Upload</div><div class="tablewrap"><table class="tbl"><thead><tr><th>RDC</th><th>Periode</th><th>Data s.d.</th><th>Rows</th><th>Mapped</th><th>Review</th><th>Status</th></tr></thead><tbody>${results.map(r=>`<tr><td>${esc(r.rdc)}</td><td>${esc(r.period)}</td><td>${esc(r.data_through_date)}</td><td>${fmt(r.total_rows)}</td><td>${fmt(r.mapped_rows)}</td><td>${fmt(r.review_rows)}</td><td>${kpiStatusPill(r.status==='READY'?'PROVISIONAL':r.status)}</td></tr>${r.review_rows?`<tr><td colspan="7"><b>Unknown:</b> ${(r.unknown_movement_types||[]).map(u=>`${esc(u.movement_type)} (${u.rows}) ${ACCESS.is_master?`<button class="secondary" onclick="editMoveMap('${esc(u.movement_type)}')">Map</button>`:''}`).join(' · ')}</td></tr>`:''}`).join('')}</tbody></table></div>`;msg.style.color=reviews?'#b65f00':'#079455';msg.textContent=reviews?`Upload berhasil, tetapi ${reviews} row memerlukan mapping sebelum KPI dapat dihitung.`:'✓ Upload berhasil. KPI Warehouse MTD diperbarui sebagai PROVISIONAL.';await loadAll()}catch(x){msg.style.color='#c42d26';msg.textContent='Gagal: '+cleanErr(x.message)}};fr.readAsBinaryString(file)}

// reconciliation wizard preserving existing v43 logic
const PLATE_RE=/\b[A-Z]{1,2}\s?\d{3,5}\s?[A-Z]{1,3}\b/;let UPLOAD=null;
function classify(dht,mvt){let t=String(dht||'').toUpperCase();if(PLATE_RE.test(t))return{main:'delivery',sub:'Transport'};if(mvt==='602')return{main:'delivery',sub:'Loading'};if(/PECAH/.test(t)&&/PALET|PALLET/.test(t))return{main:'warehouse',sub:'Packaging / Pallet'};if(/PERSIAPAN/.test(t))return{main:'warehouse',sub:'Handling / Picking'};if(/PERAPIHAN|\bSO\b|STOCK OPNAME|GUDANG/.test(t))return{main:'warehouse',sub:'Storage / Penyimpanan'};return{main:'warehouse',sub:'Other'}}
